config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/confirmation' => 'customers#confirmation'
    patch '/customers' => 'customers#update_without'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :items, only: [:index, :show]

    resources :addresses, only: [:index, :edit, :update, :create, :destroy]

    get '/orders/thanks' => 'orders#thanks'
    post '/orders/confirmation' => 'orders#confirmation'
    resources :orders, only: [:new, :create, :index, :show]
  end

  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :ordering_products, only: [:update]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end
  
  def total
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: { cancel_membership: true, validity: false }

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordering_products, dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

  def sumamount
    Item.sum(:amount)
  end

  enum is_active: { now_on_sale: true, sales_are_suspended: false }

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordering_products
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_manufacture: 2, preparing_to_ship: 3, already_shipped: 4 }
end

app/models/ordering_product.rb
class OrderingProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_produced: 0, awaiting_production: 1, under_manufacture: 2, complete_prodution: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
     @customer.update(customer_params)
     redirect_to admin_customer_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController
  def index
    @newgenre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  def top
    @orders = Order.page(params[:page])
    @ordering_products = OrderingProduct.all
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:id, :name, :image, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def show
    @customer = current_customer
    @order = Order.find(params[:id])
    @shopping_cost = 800
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end

  private
  def order_params
    params.require(:order).permit(:id, :status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
<%= form_with model: @customer, url: admin_customer_path do |f| %>
<table>
  <tr>
    <td>会員ID</td>
    <td><%= @customer.id %></td>
    <td></td>
  </tr>

  <tr>
    <td>名前</td>
    <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></td>
    <td><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></td>
  </tr>

  <tr>
    <td>フリガナ</td>
    <td><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %></td>
    <td><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %></td>
  </tr>

  <tr>
    <td>郵便番号</td>
    <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %></td>
    <td></td>
  </tr>

  <tr>
    <td>住所</td>
    <td><%= f.text_field :address, autofocus: true, autocomplete: "address" %></td>
    <td></td>
  </tr>

  <tr>
    <td>電話番号</td>
    <td><%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %></td>
    <td></td>
  </tr>

  <tr>
    <td>メールアドレス</td>
    <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
    <td></td>
  </tr>

  <tr>
    <td>会員ステータス</td>
    <td>
      <%= f.radio_button :is_deleted, "validity" %>
      <%= f.label :is_deleted, "有効" %>
    </td>
    <td>
      <%= f.radio_button :is_deleted, "cancel_membership" %>
      <%= f.label :is_deleted, "退会" %>
    </td>
  </tr>

  <tr>
    <td></td>
    <td><%= f.submit "変更を保存", class: 'btn btn-success' %></td>
    <td></td>
  </tr>
</table>
<% end %>

app/views/admin/customers/index.html.erb
<h2>会員一覧</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |f| %>
      <tr>
        <td><%= f.id %></td>
        <td>
          <%= link_to admin_customer_path(f.id) do %>
            <%= f.last_name %><%= f.first_name %>
          <% end %>
        </td>
        <td><%= f.email %></td>
        <td>
          <%= f.is_deleted_i18n %>
        </td>
      </tr>
    <% end %>
    <%= paginate @customers %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
<table>
  <tr>
    <td>会員ID<td>
    <td><%= @customer.id %><td>
  </tr>
  <tr>
    <td>氏名<td>
    <td><%= @customer.last_name %><%= @customer.first_name %><td>
  </tr>
  <tr>
    <td>フリガナ<td>
    <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %><td>
  </tr>
  <tr>
    <td>郵便番号<td>
    <td><%= @customer.postal_code %><td>
  </tr>
  <tr>
    <td>住所<td>
    <td><%= @customer.address %><td>
  </tr>
  <tr>
    <td>電話番号<td>
    <td><%= @customer.telephone_number %><td>
  </tr>
  <tr>
    <td>メールアドレス<td>
    <td><%= @customer.email %><td>
  </tr>
  <tr>
    <td>ステータス<td>
    <td>
      <%= @customer.is_deleted_i18n %>
    <td>
  </tr>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success' %>
<%= link_to "注文履歴一覧を見る", admin_path, class: 'btn btn-primary' %>

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2><br>
<%= form_with model: @genre, url: admin_genre_path do |f| %>

  <label>ジャンル名</label>
  <%= f.text_field :name %>
  <%= f.submit "変更を保存", class: 'btn btn-success' %>

<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2><br>
  <label>ジャンル名</label>
  <%= form_with model: @newgenre, url: admin_genres_path do |f| %>
    <%= f.text_field :name %>
    <%= f.submit '新規登録', class: 'btn btn-success' %>
  <% end %>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>ジャンル</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td>
        <%= genre.name %>
      </td>
      <td>
        <%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/edit.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: admin_item_path do |f| %>
<label>商品画像</label>
<%= f.file_field :image, accept: "image/*" %><br>

<label>商品名</label>
<%= f.text_field :name %><br>

<label>商品説明</label>
<%= f.text_area :introduction %><br>

<label>ジャンル</label>
<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
<br>

<label>税抜価格</label>
<%= f.text_field :price %><br>

<label>製造ステータス</label>
<%= f.radio_button :is_active, "now_on_sale" %>
<%= f.label :is_active, "販売中" %>
<%= f.radio_button :is_active, "sales_are_suspended" %>
<%= f.label :is_active, "販売停止中" %>
<br>

<%= f.submit "変更を保存", class: 'btn btn-success' %>

<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<%= link_to new_admin_item_path do %>
<i class="fas fa-solid fa-eject"></i>
<% end %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |f| %>
      <tr>
        <td><%= f.id %></td>
        <td>
          <%= link_to admin_item_path(f.id) do %>
            <%= f.name %>
          <% end %>
        </td>
        <td><%= f.price %></td>
        <td><%= f.genre.name %></td>
        <td>
          <%= Item.is_actives_i18n[f.is_active] %>
        </td>
      </tr>
    <% end %>
    <%= paginate @items %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: admin_items_path do |f| %>
<label>商品画像</label>
<%= f.file_field :image, accept: "image/*" %><br>

<label>商品名</label>
<%= f.text_field :name %><br>

<label>商品説明</label>
<%= f.text_area :introduction %><br>

<label>ジャンル</label>
<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
<br>

<label>税抜価格</label>
<%= f.text_field :price %><br>

<label>製造ステータス</label>
<%= f.radio_button :is_active, "now_on_sale" %>
<%= f.label :is_active, "販売中" %>
<%= f.radio_button :is_active, "sales_are_suspended" %>
<%= f.label :is_active, "販売停止中" %>
<br>

<%= f.submit "新規登録", class: 'btn btn-success' %>

<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<label>商品画像</label>
<%= image_tag @item.get_image(100, 100) %><br>

<label>商品名</label>
<%= @item.name %><br>

<label>商品説明</label>
<%= @item.introduction %><br>

<label>ジャンル</label>
<%= @item.genre.name %>
<br>

<label>税抜価格</label>
<%= @item.price %><br>

<label>製造ステータス</label>
<%= Item.is_actives_i18n[@item.is_active] %>
<br>

<%= link_to "編集する", edit_admin_item_path(@item.id), class: 'btn btn-success' %>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>
<table>
  <tr>
    <th>購入者</th>
    <td><%= @order.name %></td>
  </tr>
  <tr>
    <th>注文日</th>
    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>配送先</th>
    <td>
      〒<%= @order.postal_code %>
      <%= @order.address %><br>
      <%= @order.name %>
    </td>
  </tr>
  <tr>
    <th>支払方法</th>
    <td><%= @order.payment_method_i18n %></td>
  </tr>
  <tr>
    <th>注文ステータス</th>
    <td>
      <%= form_with model: @order, url: admin_order_path do |f| %>
      <%= f.select :status, Order.statuses_i18n.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
      <%= f.submit "更新", class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
</table>

<table class="table table-hover table-inverse">
  <tr>
    <th>商品名</th>
    <th>単価(税込)</th>
    <th>数量</th>
    <th>小計</th>
    <th>製作ステータス</th>
  </tr>
  <% @order.ordering_products.each do |ordering_product| %>
  <tr>
    <td><%= ordering_product.item.name %></td>
    <td><%= ordering_product.item.with_tax_price %></td>
    <td><%= ordering_product.amount %></td>
    <td><%= ordering_product.item.with_tax_price * ordering_product.amount %></td>
    <td>
    <%= form_with model: ordering_product, url: admin_ordering_product_path(ordering_product.id) do |m| %>

      <%= m.select :making_status, OrderingProduct.making_statuses_i18n.keys.map {|k| [I18n.t("enums.ordering_product.making_status.#{k}"), k]} %>
      <%= m.submit "更新", class: "btn btn-success" %>

    <% end %>
    </td>
  </tr>
  <% end %>
</table>
<table>
  <tr>
    <th>商品合計</th>
    <td><%= @order.total_payment - @order.shopping_cost %>円</td>
  </tr>
  <tr>
    <th>送料</th>
    <td><%= @order.shopping_cost %>円</td>
  </tr>
  <tr>
    <th>請求金額合計</th>
    <td><%= @order.total_payment %>円</td>
  </tr>
</table>