config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/confirmation' => 'customers#confirmation'
    patch '/customers' => 'customers#update_without'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :items, only: [:index, :show]

    resources :addresses, only: [:index, :edit, :update, :create, :destroy]

    get '/orders/thanks' => 'orders#thanks'
    post '/orders/confirmation' => 'orders#confirmation'
    resources :orders, only: [:new, :create, :index, :show]
  end

  get '/admin' => 'admin/homes#top'

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :ordering_products, only: [:update]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end
  
  def total
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: { cancel_membership: true, validity: false }

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordering_products, dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

  def sumamount
    Item.sum(:amount)
  end

  enum is_active: { now_on_sale: true, sales_are_suspended: false }

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordering_products
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, under_manufacture: 2, preparing_to_ship: 3, already_shipped: 4 }
end

app/models/ordering_product.rb
class OrderingProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_produced: 0, awaiting_production: 1, under_manufacture: 2, complete_prodution: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController
  def index
    @newgenre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  def top
    @orders = Order.page(params[:page])
    @ordering_products = OrderingProduct.all
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:id, :name, :image, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def show
    @customer = current_customer
    @order = Order.find(params[:id])
    @shopping_cost = 800
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end

  private
  def order_params
    params.require(:order).permit(:id, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand">
              <i class="fa-solid fa-cake-candles"></i> ロゴ
          </a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧", admin_items_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn nav-link text-black' %>
              </li>

              <% elsif customer_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", customers_mypage_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "カート", cart_items_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn nav-link text-black' %>
              </li>

              <% else %>

              <li class="nav-item">
                <%= link_to "About", about_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'btn nav-link text-black' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", customer_session_path, class: 'btn nav-link text-black' %>
              </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>